---
  - name: Install MySQL
    hosts: localhost
    tasks:
    - name: apt  Install mysql package in ansible
      ansible.builtin.apt:
        name: mysql-server
        state: present
      become: true
