---
  - name: Install MySQL
    hosts: localhost
    become: yes
    become_user: root
    gather_facts: false
    tasks:
    - name: apt  Install mysql package in ansible
      ansible.builtin.yum:
        name: mysql-server
        state: present
